/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_tursom_unsafe_NetUtils */

#ifndef _Included_cn_tursom_unsafe_NetUtils
#define _Included_cn_tursom_unsafe_NetUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([C)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3C
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3S
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3J
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([C[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3C_3BI
  (JNIEnv *, jobject, jcharArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([S[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3S_3BI
  (JNIEnv *, jobject, jshortArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([I[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3I_3BI
  (JNIEnv *, jobject, jintArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toByteArray
 * Signature: ([J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_unsafe_NetUtils_toByteArray___3J_3BI
  (JNIEnv *, jobject, jlongArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toCharArray
 * Signature: ([B)[C
 */
JNIEXPORT jcharArray JNICALL Java_cn_tursom_unsafe_NetUtils_toCharArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toShortArray
 * Signature: ([B)[S
 */
JNIEXPORT jshortArray JNICALL Java_cn_tursom_unsafe_NetUtils_toShortArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toIntArray
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_tursom_unsafe_NetUtils_toIntArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toLongArray
 * Signature: ([B)[J
 */
JNIEXPORT jlongArray JNICALL Java_cn_tursom_unsafe_NetUtils_toLongArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toChar
 * Signature: ([BI)C
 */
JNIEXPORT jchar JNICALL Java_cn_tursom_unsafe_NetUtils_toChar
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toShort
 * Signature: ([BI)S
 */
JNIEXPORT jshort JNICALL Java_cn_tursom_unsafe_NetUtils_toShort
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toInt
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_cn_tursom_unsafe_NetUtils_toInt
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    toLong
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_cn_tursom_unsafe_NetUtils_toLong
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    ntoh
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_cn_tursom_unsafe_NetUtils_ntoh__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    hton
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_cn_tursom_unsafe_NetUtils_hton__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    ntoh
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_tursom_unsafe_NetUtils_ntoh__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    hton
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_tursom_unsafe_NetUtils_hton__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    ntoh
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_tursom_unsafe_NetUtils_ntoh__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_tursom_unsafe_NetUtils
 * Method:    hton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_tursom_unsafe_NetUtils_hton__J
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
