/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_tursom_data_DataKt */

#ifndef _Included_cn_tursom_data_DataKt
#define _Included_cn_tursom_data_DataKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([C)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_data_DataKt_toByteArray___3C
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_data_DataKt_toByteArray___3S
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_data_DataKt_toByteArray___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_tursom_data_DataKt_toByteArray___3J
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([C[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_data_DataKt_toByteArray___3C_3BI
  (JNIEnv *, jclass, jcharArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([S[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_data_DataKt_toByteArray___3S_3BI
  (JNIEnv *, jclass, jshortArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([I[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_data_DataKt_toByteArray___3I_3BI
  (JNIEnv *, jclass, jintArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toByteArray
 * Signature: ([J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_tursom_data_DataKt_toByteArray___3J_3BI
  (JNIEnv *, jclass, jlongArray, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toCharArray
 * Signature: ([B)[C
 */
JNIEXPORT jcharArray JNICALL Java_cn_tursom_data_DataKt_toCharArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toShortArray
 * Signature: ([B)[S
 */
JNIEXPORT jshortArray JNICALL Java_cn_tursom_data_DataKt_toShortArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toIntArray
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_tursom_data_DataKt_toIntArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toLongArray
 * Signature: ([B)[J
 */
JNIEXPORT jlongArray JNICALL Java_cn_tursom_data_DataKt_toLongArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toChar
 * Signature: ([BI)C
 */
JNIEXPORT jchar JNICALL Java_cn_tursom_data_DataKt_toChar
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toShort
 * Signature: ([BI)S
 */
JNIEXPORT jshort JNICALL Java_cn_tursom_data_DataKt_toShort
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toInt
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_cn_tursom_data_DataKt_toInt
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    toLong
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_cn_tursom_data_DataKt_toLong
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    ntoh
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_cn_tursom_data_DataKt_ntoh__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    hton
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_cn_tursom_data_DataKt_hton__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    ntoh
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_tursom_data_DataKt_ntoh__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    hton
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_tursom_data_DataKt_hton__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    ntoh
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_tursom_data_DataKt_ntoh__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_tursom_data_DataKt
 * Method:    hton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cn_tursom_data_DataKt_hton__J
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
